// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvblWg42Ozg_nnVbClLxMLsJkOTJrsFC0',
    appId: '1:167468065470:web:13d40d03a637f5a6f234ef',
    messagingSenderId: '167468065470',
    projectId: 'doctor-care-498d5',
    authDomain: 'doctor-care-498d5.firebaseapp.com',
    storageBucket: 'doctor-care-498d5.appspot.com',
    measurementId: 'G-1ERFWKFLBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFmt3J4yCTacEVl00Q-ZjId6u1hpAbdc0',
    appId: '1:167468065470:android:6c58da7da79442e8f234ef',
    messagingSenderId: '167468065470',
    projectId: 'doctor-care-498d5',
    storageBucket: 'doctor-care-498d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKK12WruaB9jS_nV0SjWWtcHCgAZ_8Cf4',
    appId: '1:167468065470:ios:09717ebd2d0f5b6ef234ef',
    messagingSenderId: '167468065470',
    projectId: 'doctor-care-498d5',
    storageBucket: 'doctor-care-498d5.appspot.com',
    iosClientId: '167468065470-se6pt57jvucemte8o6rkav57m207t5ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKK12WruaB9jS_nV0SjWWtcHCgAZ_8Cf4',
    appId: '1:167468065470:ios:09717ebd2d0f5b6ef234ef',
    messagingSenderId: '167468065470',
    projectId: 'doctor-care-498d5',
    storageBucket: 'doctor-care-498d5.appspot.com',
    iosClientId: '167468065470-se6pt57jvucemte8o6rkav57m207t5ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorcare',
  );
}
